### ISSUE TITLE
Add a configuration option for inverted mouse wheel zoom

### ISSUE THREAD

**Issue by Zakru** [DigitalExtinction/Game#479]
Currently the mouse wheel zooms in when scrolled down and out when scrolled up. At least in my experience, most software uses the opposite controls, so I think there should at least be a configuration option to change that.

**Comment by JackCrumpLeys** [comment]
Have a look at the `Camera` struct in the conf crate. We need a bool probably and a default of false. Macros handle the de-serialising (read pr  [#453](https://github.com/DigitalExtinction/Game/pull/453)) so should be easy. 

Then have a look at how the camera crate reads config (you will want to make a get method). I will do this later in the weekend if you don't want to.
