### ISSUE TITLE
Change license from GPLv3 to AGPLv3

### ISSUE THREAD

**Issue by Indy2222** [DigitalExtinction/Game#645]
Change the license of all source code from GPLv3 to [AGPLv3](https://www.gnu.org/licenses/agpl-3.0.en.html).

# Reasoning

A significant portion of the source code involves both the DE Connector (server) and DE Lobby (server), which operate over the network. With the advent of cloud gaming, the game itself might be played over the network. The reasons for original choosing of GPL are applicable to the game's over the network usage and thus the motivation for switch from GPL to AGPL.

# Legal

This must be agreed by all authors (below). Please state you explicit agreement in a comment:

```markdown
I am writing to formally express my agreement to the relicensing of my code contributions to the [Digital Extinction](https://github.com/DigitalExtinction/Game) from the GNU General Public License v3 (GPL) to the [GNU Affero General Public License v3 (AGPLv3)](https://www.gnu.org/licenses/agpl-3.0.en.html).
```

- [x] @Indy2222 
- [x] @JackCrumpLeys 
- [x] @0HyperCube 
- [x] @Polostor 
- [x] @Zakru 
- [x] @Vrixyz

**Comment by Indy2222** [comment]
I am writing to formally express my agreement to the relicensing of my code contributions to the [Digital Extinction](https://github.com/DigitalExtinction) from the GNU General Public License v3 (GPL) to the [GNU Affero General Public License v3 (AGPLv3)](https://www.gnu.org/licenses/agpl-3.0.en.html).

**Comment by Vrixyz** [comment]
I am writing to formally express my agreement to the relicensing of my code contributions to the Digital Extinction from the GNU General Public License v3 (GPL) to the GNU Affero General Public License v3 (AGPLv3).

**Comment by Zakru** [comment]
I am writing to formally express my agreement to the relicensing of my code contributions to the [Digital Extinction](https://github.com/DigitalExtinction/Game) from the GNU General Public License v3 (GPL) to the [GNU Affero General Public License v3 (AGPLv3)](https://www.gnu.org/licenses/agpl-3.0.en.html).

**Comment by JackCrumpLeys** [comment]
I am writing to formally express my agreement to the relicensing of my code contributions to the [Digital Extinction](https://github.com/DigitalExtinction/Game) from the GNU General Public License v3 (GPL) to the [GNU Affero General Public License v3 (AGPLv3)](https://www.gnu.org/licenses/agpl-3.0.en.html).

**Comment by 0HyperCube** [comment]
I am writing to formally express my agreement to the relicensing of my code contributions to the [Digital Extinction](https://github.com/DigitalExtinction/Game) from the GNU General Public License v3 (GPL) to the [GNU Affero General Public License v3 (AGPLv3)](https://www.gnu.org/licenses/agpl-3.0.en.html).
